modLoader="javafml"
loaderVersion="[34,)"
license="All rights reserved"

issueTrackerURL="https://github.com/MrCrayfish/GoblinTraders/issues"

[[mods]]
modId="goblintraders"
version="1.2.2"
displayName="Goblin Traders"
updateJSONURL="https://raw.githubusercontent.com/MrCrayfish/ModUpdates/master/goblintraders/update.json"
displayURL="https://mrcrayfish.com/mods?id=goblintraders"
logoFile="goblintraders.png"
credits="@ItsNahteTV on Twitter for idea. Thank you to @MCVinnyq for creating goblin model"
authors="MrCrayfish"
description='Adds goblins that trade speical items with the player!'

[[dependencies.goblintraders]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.goblintraders]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.17)"
    ordering="NONE"
    side="BOTH"
